models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{

    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

models/Users.php
<?php

namespace app\models;

use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $login
 * @property string $name
 * @property string $sex
 * @property string $created_at
 * @property string $email
 * @property int $status
 * @property string $surname
 * @property object $addresses
 * @property string $updated_at
 * @property string $password
 *
 */
class Users extends \yii\db\ActiveRecord
{

    const FEMALE = 'female';
    const MALE = 'male';
    const UNKNOWN = 'unknown';
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['login', 'name', 'surname','sex', 'email','password'], 'required'],
            [['created_at','updated_at'], 'safe'],
            [['status'], 'integer'],
            [['login', 'email'], 'string', 'max' => 150],
            [['name','surname'], 'string', 'max' => 100],
            [['sex', 'password'], 'string', 'max' => 50],
            [['email','login'], 'unique'],
            [['login'], 'string', 'min' => 4],
            [['password'], 'string', 'min' => 6],
            [
                ['name', 'surname'],
                \cetver\ValidationFilters\validators\MultibyteUpperCharacterFirstValidator::class,
                'encoding' => 'UTF-8'
            ]
        ];
    }

    public static function sex_list()
    {
        return [
            self::FEMALE => Yii::t('users', 'Female'),
            self::MALE => Yii::t('users', 'Male'),
            self::UNKNOWN => Yii::t('users', 'Unknown'),
        ];

    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Login',
            'password' => 'Password',
            'name' => 'Name',
            'sex' => 'Sex',
            'surname' => 'Surname',
            'created_at' => 'Created At',
            'updated_at' => 'Created At',
            'email' => 'Email',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestampBehavior' => [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
            'saveRelations' => [
                'class' => SaveRelationsBehavior::class,
                'relations' => [
                    'addresses',
                ],
            ],
        ];
    }

//Использовать транзакции для SaveRelationsBehavior
    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL,
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddresses()
    {
        return $this->hasMany(ShippingAddress::class, ['user_id' => 'id']);
    }

    public function getAddress($id)
    {

    }

    public static function getStatuses()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('users', 'Publish'),
            self::STATUS_INACTIVE => Yii::t('users', 'Unpublish'),
        ];
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\ShippingAddress;
use lhs\Yii2SaveRelationsBehavior\SaveRelationsTrait;
use Yii;
use app\models\Users;
use app\models\search\UsersSearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for Users model.
 *
 * @property ShippingAddress $shippingAddress
 */
class UsersController extends Controller
{
    use SaveRelationsTrait;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'addreses' => $shipping,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $addresses = $this->getUserAddresses($id);
        $dataProvider = new ArrayDataProvider([
            'allModels' => $addresses,
            'pagination' => [
                'pageSize' => 5,
            ]
        ]);
        return $this->render('view', [
            'dataProvider' => $dataProvider,
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $users = new Users();
        $shipping = new ShippingAddress();
        $users->addresses = $shipping;
        if ($users->load(Yii::$app->request->post()) && $shipping->load(Yii::$app->request->post()) && $users->save()) {

            return $this->redirect(['view', 'id' => $users->id]);
        }

        return $this->render('create', [
            'model' => $users,
            'shipping' => $shipping
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $users = $this->findModel($id);
        $shipping = $this->getUserAddresses($id);
        $users->addresses = $shipping;
        if ($users->load(Yii::$app->request->post()) && $users->save()) {
            return $this->redirect(['view', 'id' => $users->id]);
        }

        return $this->render('update', [
            'model' => $users,
            'shipping' => $shipping,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionAddAddress($id)
    {
        $address = new ShippingAddress();
        $address->user_id = $id;
        $user = $this->findModel($id);
        if($address->load(Yii::$app->request->post()) && $address->save(false)){
            return $this->redirect(['/users/view', 'id' => $address->user_id]);
        }
        return $this->render('/shipping/create',[
            'model' => $address,
            'user' => $user,
        ]);
    }

    public function actionAddressDelete($id, $user_id)
    {
        ShippingAddress::findOne(['id' => $id])->delete();

        return $this->redirect(['/users/view', 'id' => $user_id]);

    }
    public function actionAddressUpdate($id, $user_id)
    {
        $address = ShippingAddress::findOne($id);
        $user = $this->findModel($user_id);
        if ($address->load(Yii::$app->request->post()) && $address->save(false)) {
            return $this->redirect(['view', 'id' => $user_id]);
        }
        return $this->render('/shipping/update', [
            'user' => $user,
            'model' => $address,
        ]);

    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    private function getUserAddresses($user_id)
    {
        $shipping = new ShippingAddress();
        return $shipping->getUserAddresses($user_id);
    }


}

views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
/* @var $shipping \app\models\ShippingAddress*/
?>

<div class="box-body table-responsive">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active">
            <a data-toggle="tab" href="#user" href="#">
                <?= Yii::t('users', 'User'); ?>
            </a>
        </li>
        <li role="presentation">
            <a data-toggle="tab" href="#shipping" href="#">
                <?= Yii::t('users', 'Shipping'); ?>
            </a>
        </li>
    </ul>
    <?php $form = ActiveForm::begin(); ?>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="user">
            <div class="box-body">

                <?= $form->field($model, 'login')->textInput(['maxLength' => true]) ?>

                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'password')->textInput(['maxlength' => true, 'minLength' => true]) ?>

                <?= $form->field($model, 'sex')->dropDownList(\app\models\Users::sex_list()) ?>

                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'status')->dropDownList(\app\models\Users::getStatuses()) ?>


            </div>
        </div>
        <? if(is_array($shipping)):?>
        <? foreach ($shipping as $item):?>
        <div role="tabpanel" class="tab-pane" id="shipping">
            <div class="box-body">
                <?= $form->field($item, 'postcode')->textInput(['maxlength' => true]) ?>

                <?= $form->field($item, 'country')->textInput(['maxlength' => true]) ?>

                <?= $form->field($item, 'city')->textInput(['maxlength' => true]) ?>

                <?= $form->field($item, 'street')->textInput() ?>

                <?= $form->field($item, 'house')->textInput(['maxlength' => true]) ?>

                <?= $form->field($item, 'apartment')->textInput() ?>

                <?= $form->field($item, 'status')->dropDownList(\app\models\Users::getStatuses()) ?>




            </div>
        </div>
        <? endforeach;?>
        <? endif;?>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/users/_form_create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
/* @var $shipping \app\models\ShippingAddress*/
?>

<div class="box-body table-responsive">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active">
            <a data-toggle="tab" href="#user" href="#">
                <?= Yii::t('users', 'User'); ?>
            </a>
        </li>
        <li role="presentation">
            <a data-toggle="tab" href="#shipping" href="#">
                <?= Yii::t('users', 'Shipping'); ?>
            </a>
        </li>
    </ul>
    <?php $form = ActiveForm::begin(); ?>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="user">
            <div class="box-body">

<?// var_dump($model)?>
                <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'password')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'sex')->dropDownList(\app\models\Users::sex_list()) ?>

                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'status')->dropDownList(\app\models\Users::getStatuses()) ?>


            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="shipping">
            <div class="box-body">
                <?= $form->field($shipping, 'postcode')->textInput(['maxlength' => true]) ?>

                <?= $form->field($shipping, 'country')->textInput(['maxlength' => true]) ?>

                <?= $form->field($shipping, 'city')->textInput(['maxlength' => true]) ?>

                <?= $form->field($shipping, 'street')->textInput() ?>

                <?= $form->field($shipping, 'house')->textInput(['maxlength' => true]) ?>

                <?= $form->field($shipping, 'apartment')->textInput() ?>

                <?= $form->field($shipping, 'status')->dropDownList(\app\models\Users::getStatuses()) ?>




            </div>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'post',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'login') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'sex') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $shipping app\models\ShippingAddress */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_create', [
        'model' => $model,
        'shipping' => $shipping
    ]) ?>

</div>

views/users/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('<span class="glyphicon glyphicon-plus" style="margin-right: 0.5em;"></span>Create User', ['create'], ['class' => 'btn btn-success', 'data-method' => 'POST']) ?>
    </p>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <?= Yii::t('users', 'Users List') ?>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            <?= ListView::widget([
                                'dataProvider' => $dataProvider,
                                'itemOptions' => ['class' => 'item'],
                                'itemView' => 'list_view',
                                'summary' => '',
                                'pager' => [
                                    'pagination' => $dataProvider->setPagination(['pageSize' => 5]),
                                ]

                            ]) ?>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

views/users/list_view.php
<?php

/**
 *
 * @var $model \app\models\Users
 */

use yii\helpers\Html; ?>
<li class="list-group-item">
    <div class="checkbox">
        <?= Html::a($model->name,\yii\helpers\Url::to(['view', 'id' => $model->id]))?>
    </div>
    <div class="pull-right action-buttons">
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>',\yii\helpers\Url::to(['update', 'id' => $model->id]),['data-method' => 'POST'])?>
        <?= Html::a('<span class="glyphicon glyphicon-trash"></span>',\yii\helpers\Url::to(['delete', 'id' => $model->id]),['class' => 'trash','data' => [
            'confirm' => 'Are you sure you want to delete this item?',
            'method' => 'post',
        ],])?>

    </div>
</li>

views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $shipping \app\models\ShippingAddress */

$this->title = 'Update Users: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'shipping' => $shipping,
    ]) ?>

</div>

views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $dataProvider app\models\ShippingAddress */

$this->title = $model->name . ' ' . $model->surname;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="users-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary', 'data-method' => 'POST']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'login',
            'name',
            'surname',
            'sex',
            [
                    'attribute' => 'created_at',
                    'format' => ['datetime', 'php:d-m-Y g:i a'],
            ],
            'email:email',
            [
                'label' => 'Status',
                'value' => function ($model) {
                    return \app\models\Users::getStatuses()[$model->status];
                }
            ]
        ],
    ]) ?>
    <h2><?= Yii::t('users', 'Addresses List') ?></h2>
    <?= Html::a('<span class="glyphicon glyphicon-plus" style="margin-right: 0.5em;"></span>Add', ['/users/add-address', 'id' => $model->id], ['data' => ['method' => 'POST'], 'class' => 'btn btn-info']); ?>
    <div class="table-responsive"><?= \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'summary' => '',
            'tableOptions' => ['class' => 'table table-striped table-bordered'],
            'columns' => [
                    'id',
                'postcode',
                'country',
                'street',
                'city',
                'house',
                'apartment',
                [
                    'label' => 'status',
                    'value' => function ($dataProvider) {
                        return \app\models\Users::getStatuses()[$dataProvider->status];
                    }
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => 'Remove/Update',
                    'template' => '{address-update} {address-delete}',
                    'buttons' => [
                        'address-update' => function ($url,$dataProvider) {
                            $url = '/users/address-update?id='.$dataProvider->id.'&user_id='.$dataProvider->user_id;
                            return Html::a(
                                '<span class="glyphicon glyphicon-pencil"></span>', [$url]);
                        },
                        'address-delete' => function ($url, $dataProvider) {
                            $url = '/users/address-delete?id='.$dataProvider->id.'&user_id='.$dataProvider->user_id;
                            return Html::a(
                                '<span class="glyphicon glyphicon-trash"></span>', [$url],['data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                                    ]);
                        },

                    ],

                ],
            ]
        ]);
        ?>
    </div>
</div>